version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: php-fpm
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '8080:80'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.3.9
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_DATABASE: ${APP_NAME:?err}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql:/var/lib/mysql
